services:
  app:
    build: .
    container_name: krystle_text_msg
    command: uvicorn main:app --host 0.0.0.0 --port 666 --reload
    ports:
      - 666:666
    volumes:
      - .:/krystle_text_msg_app
